# Generated by Django 4.2.8 on 2023-12-21 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0005_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtopic',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
