# Generated by Django 5.0 on 2023-12-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0006_alter_mathtopic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='math_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bard.mathtopic'),
        ),
    ]
