# Generated by Django 5.0 on 2023-12-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0009_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
