# Generated by Django 5.0 on 2023-12-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0010_usertestresult_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
    ]
