# Generated by Django 5.0 on 2023-12-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0012_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
