# Generated by Django 5.0 on 2023-12-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0013_topic_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
