# Generated by Django 5.0 on 2023-12-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0019_userprofile_role_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
