# Generated by Django 5.0 on 2023-12-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0020_remove_userprofile_role_delete_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
