# Generated by Django 5.0 on 2023-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0023_remove_classroom_students_alter_classroom_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='bard.classroom'),
        ),
    ]
