# Generated by Django 5.0 on 2023-12-27 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0024_userprofile_classrooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
