# Generated by Django 5.0 on 2023-12-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0025_remove_userprofile_classrooms_userprofile_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='bard.classroom'),
        ),
    ]
