# Generated by Django 5.0 on 2023-12-28 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0027_remove_userprofile_students_classroom_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'teacher')},
        ),
    ]
