# Generated by Django 5.0 on 2023-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0028_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
