# Generated by Django 5.0 on 2023-12-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0029_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
    ]
