# Generated by Django 5.0 on 2024-01-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0033_remove_women_cat_test_math_topic_alter_test_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='math_topic',
        ),
    ]
