# Generated by Django 5.0 on 2024-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0039_tempregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempregistration',
            name='confirmation_code',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
    ]
