# Generated by Django 5.0 on 2024-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0042_customuser_delete_tempregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
