# Generated by Django 5.0 on 2024-01-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0043_alter_confirmationcode_code_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
