# Generated by Django 5.0 on 2024-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0045_testresult_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
