# Generated by Django 4.2.8 on 2024-01-21 17:42

import bard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0046_alter_testresult_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='date_taken',
            field=models.DateTimeField(default=bard.models.get_default_date_taken),
        ),
    ]
